### ISSUE TITLE
suggestion to improve the readability of app.py file

### ISSUE THREAD

**Issue by ojanenmarianna** [bntti/tietokantasovellus#1]
Good job so far! Application is easy to use and has all the functionalities mentioned in projects readme file.
Have you considered dividing functionalities from app.py file into two or more files (for example users.py) like in the courses reference project. Or could you make more use of the functionalities.py file. It would make the app.py file easier to read.

**Comment by bntti** [comment]
The functionalities have now been divided from app.py and database.py to multiple different files.
